// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (a *Activity) Timesheets(ctx context.Context) ([]*Timesheet, error) {
	result, err := a.Edges.TimesheetsOrErr()
	if IsNotLoaded(err) {
		result, err = a.QueryTimesheets().All(ctx)
	}
	return result, err
}

func (a *Activity) Project(ctx context.Context) (*Project, error) {
	result, err := a.Edges.ProjectOrErr()
	if IsNotLoaded(err) {
		result, err = a.QueryProject().Only(ctx)
	}
	return result, err
}

func (pr *Project) Activities(ctx context.Context) ([]*Activity, error) {
	result, err := pr.Edges.ActivitiesOrErr()
	if IsNotLoaded(err) {
		result, err = pr.QueryActivities().All(ctx)
	}
	return result, err
}

func (t *Timesheet) Activity(ctx context.Context) (*Activity, error) {
	result, err := t.Edges.ActivityOrErr()
	if IsNotLoaded(err) {
		result, err = t.QueryActivity().Only(ctx)
	}
	return result, err
}
