// Code generated by entc, DO NOT EDIT.

package ent

import (
	"alwayslate/ent/schema/pulid"
	"alwayslate/ent/user"
	"context"
	"fmt"
	"strings"
)

// prefixMap maps PULID prefixes to table names.
var prefixMap = map[pulid.ID]string{
	"user": user.Table,
}

// IDToType maps a pulid.ID to the underlying table.
func IDToType(ctx context.Context, id pulid.ID) (string, error) {
	strs := strings.Split(string(id), ":")
	if len(strs) < 2 {
		return "", fmt.Errorf("IDToType: invalid id: '%s'", id)
	}

	typ := prefixMap[pulid.ID(strs[0])]
	if typ == "" {
		return "", fmt.Errorf("IDToType: could not map prefix '%s' to a type", strs[0])
	}

	return typ, nil
}
