// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Activity is the predicate function for activity builders.
type Activity func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Timesheet is the predicate function for timesheet builders.
type Timesheet func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
